import "./blocks/post-title";
import "./blocks/post-excerpt";
import "./blocks/read-more";
import "./blocks/post-featured-image";
import "./blocks/post-author";
import "./blocks/post-author-fields";
import "./blocks/post-categories";
import "./blocks/post-tags";
import "./blocks/post-taxonomies";
import "./blocks/post-date";
import "./blocks/post-meta";
import "./blocks/post-comment-count";
import "./blocks/post-comments";
import "./blocks/archive-title";
import "./blocks/archive-description";
import "./blocks/table-of-contents";
import "./blocks/image";
import "./blocks/post-grid";
import "./blocks/filterable-grid";
import "./blocks/";
import "./blocks/post-query";
import "./blocks/post-query-pagination";
import "./blocks/content-slider";
import "./blocks/content-slider-item";
import "./blocks/popup";
import "./blocks/user-query";
import "./blocks/user-fields";
import "./blocks/user-query-pagination";
import "./blocks/form-wrap";
import "./blocks/form-steps";
import "./blocks/form-field-simple-math";
import "./blocks/form-field-input";
import "./blocks/form-field-submit";
import "./blocks/form-field-select";
import "./blocks/form-field-checkbox";
import "./blocks/form-field-radio";
import "./blocks/form-field-textarea";
import "./blocks/form-field-file";
import "./blocks/form-field-recaptcha";
import "./blocks/number-counter";
import "./blocks/date-countdown";
import "./blocks/list";
import "./blocks/list-nested";
import "./blocks/list-nested-item";
import "./blocks/progress-bar";
import "./blocks/menu-wrap";
import "./blocks/menu-wrap-item";
import "./blocks/icon";
import "./blocks/text";
import "./blocks/star-rate";
import "./blocks/breadcrumb";
import "./blocks/shortcode";
import "./blocks/social-share";
import "./blocks/terms-list";
import "./blocks/terms-query";
import "./blocks/terms-query-item";
import "./blocks/back-to-top";
import "./blocks/flip-box";
import "./blocks/flip-box-front";
import "./blocks/flip-box-back";
import "./blocks/layers";
import "./blocks/layer";
import "./blocks/grid-wrap";
import "./blocks/grid-wrap-item";
import "./blocks/flex-wrap";
import "./blocks/flex-wrap-item";
import "./blocks/masonry-wrap";
import "./blocks/masonry-wrap-item";
import "./blocks/team-showcase";
import "./blocks/team-members";
import "./blocks/team-members-field";
import "./blocks/testimonial-showcase";
import "./blocks/testimonials";
import "./blocks/testimonials-field";
import "./blocks/business-hours";
import "./blocks/info-box";
import "./blocks/info-box-item";
import "./blocks/table";
import "./blocks/table-td";
import "./blocks/table-tr";
import "./blocks/image-gallery";
import "./blocks/image-gallery-item";
import "./blocks/images";
import "./blocks/images-field";
import "./blocks/accordion-nested";
import "./blocks/accordion-nested-item";
import "./blocks/image-accordion";
import "./blocks/image-accordion";
import "./blocks/tabs-nested";
import "./blocks/tabs-nested-item";
import "./blocks/wordpress-org";
import "./blocks/wordpress-org-item";
import "./blocks/woo-sku";
import "./blocks/woo-total-sales";
import "./blocks/woo-stock-quantity";
import "./blocks/woo-product-info";
import "./blocks/woo-product-info-item";
import "./blocks/woo-price";
import "./blocks/woo-sale";
import "./blocks/woo-stock";
import "./blocks/woo-star-rate";
import "./blocks/woo-add-to-cart";

// const addBlockEditAttributes = createHigherOrderComponent((BlockEdit) => {
//     return (props) => {
//         const { attributes, setAttributes, clientId } = props;
//         const {
//             blockId,
//         } = attributes;
//         //props.attributes.blockId = 'pg' + clientId.split('-').pop();
//         return <BlockEdit {...props} />;
//     };
// }, 'addBlockEditAttributes');
// addFilter(
//     'editor.BlockEdit',
//     'combo-blocks/text',
//     addBlockEditAttributes
// );
// addFilter(
//     'editor.BlockEdit',
//     'combo-blocks/layers',
//     addBlockEditAttributes
// );
